### ISSUE TITLE
Include changes from QuantumCitations.jl

### ISSUE THREAD

**Issue by fredrikekre** [JuliaDocs/DocumenterCitations.jl#1]
See https://github.com/JuliaQuantumControl/QuantumCitations.jl. Personally I think everything there should be included here. Perhaps it would be easier to rename that repository and move it here instead if replaying all commits? Thoughts @goerz?

**Comment by fredrikekre** [comment]
Given that the commit histories are completely disjoint now, one option would be to do the following:
1. Make a commit to this repo which simply deletes everything
2. Replay all current commits in https://github.com/JuliaQuantumControl/QuantumCitations.jl in this repository

This would preserve the full "history" inside this repo, which I think would be a nice thing to do. I did this once for https://github.com/JuliaSparse/Metis.jl in https://github.com/JuliaSparse/Metis.jl/pull/29

**Comment by goerz** [comment]
Oh, right, I forgot I did a "hard fork". The "initial commit" of QuantumCitations is a copy of https://github.com/ali-ramadhan/DocumenterCitations.jl/tree/fb9e2c253c6b714379990e99636a4d815dea95fc, though, so I can restore this as a proper branch for the QuantumCitations code off DocumenterCitations, and thus keep the full history of both repositories.

On that branch, I'd also have to make additional changes to properly rename QuantumCitations back to DocumenterCitations. This includes changing the name in the README and documentation, but also changing the discussion away from "this is a fork DocumenterCitations with these additional features…"), as well as changes to the CI setup.

There are two caveats:

* Do we want to keep DocumenterCitations' current default author-year style citation? As far as the QuantumCitations code is concerned, this is trivial (just change the default `style=:numeric` to `style=:authoryear`), but obviously https://juliaquantumcontrol.github.io/QuantumCitations.jl/stable/syntax/ should be adapted to illustrate whatever the default style is. Changing to author-year as the default would create the least amount of friction for existing DocumenterCitations users, but takes more work on my end to rewrite the documentation.

* Should we wait for Documenter 0.28 to come out? The plugin will have to adapt fairly substantially to the new Documenter internals, and if we're doing one big change-almost-everything-PR, we might as well do everything at once. On the other hand, if Documenter 0.28 isn't coming out for a while, or if we foresee that a lot of people will want to stick to Documenter 0.27.x for some time, we could also merge the projects now, and then adapt to the new Documenter internals separately.

I'm not sure if I'll get around to updating the documentation for the merge before JuliaCon, so we have some time to think about this.

**Comment by fredrikekre** [comment]
I like numeric as the default, but it is easy to customize anyway so it doesn't matter much. I would assume we would make a new release anyway, so I think it is fine to change the default if you want.

I started looking at upgrading to 0.28 (well, 1.0) at least, I don't expect any more breaking changes. Might not be worth it to get a more full featured DocumenterCitations package out for 0.27. Can point people to your package in that case.

**Comment by fredrikekre** [comment]
If you don't mind, I am happy to give the history merge a go.

**Comment by Krastanov** [comment]
Just wanted to say thank you, guys! I really appreciate someone is taking care of this!
