### ISSUE TITLE
Incompatible with `linkcheck`

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/DocumenterCitations.jl#19]
*Transferred from https://github.com/JuliaQuantumControl/QuantumCitations.jl/issues/11*

This plugin is incompatible with the `linkcheck` option to `makedocs`.

This may or may not be fixed by #3

**Comment by fredrikekre** [comment]
Incompatible in what sense? Just that linkcheck errors for citation links?

**Comment by goerz** [comment]
Yes, I think so
