### ISSUE TITLE
Note = not displayed (or: add customs fields in display of a BibteX entry)

### ISSUE THREAD

**Issue by kellertuer** [JuliaDocs/DocumenterCitations.jl#20]
I would like to add notes to references to mention open access preprints (since we have BibTeX and not BibLaTeX where I could use eprint=), but if I provide a `note=` field, this is not shown in the `:alpha` style. Is there an easy trick to add this (i.e. a modification / an own style)?
Or is that something where Bibliography takes care of the rendering?

**Comment by goerz** [comment]
If you want a dirty hack, you can just overwrite the `format_bibliography_reference` method

https://github.com/JuliaDocs/DocumenterCitations.jl/blob/fe4ca7036b18b4a9bef2f21a57e486fadfe05326/src/bibliography.jl#L60-L66

This is not considered part of the public/stable API, of course.

I'd definitely be open to including the Note field. Generally, I've tried to mimic RevTeX as much as possible, based on [these test files](https://github.com/JuliaDocs/DocumenterCitations.jl/tree/master/docs/latex) (up to some small improvements like italicizing titles and putting last names first in the author-year bibliographies). RevTeX will print `Note` fields in these examples, so I think we should as well. Consider the feature requested for the next version!

Can you give an example for what you typically put in the `note` field in this case? Specifically, do you include any kind of URL? As I [mentioned before](https://github.com/JuliaDocs/DocumenterCitations.jl/tree/master/docs/latex), there is the potential issue that for real LaTeX, all strings are rendered through the TeX engine, whereas here, they get some minimal cleanup and are then considered plain text or markdown. So support for something like `\url` might be tricky.

**Comment by kellertuer** [comment]
I am currently stepping away from the automatic export I considered before, since most my “original data” is BibLaTeX anyways. What I would like to add/mimic is the mentioning of open access preprints.

The example is

https://github.com/JuliaManifolds/Manopt.jl/blob/98adc93e1ebb1982562a87caefac481401e18ac3/docs/src/references.bib#L61

And for the reason mentioned above, I directly went for Markdown links and not URL links.
(The idea is that later when one has BibLaTeX I would switch these back to my original entries that use `eprint` and `eprinttype` fields from BibLaTeX). So Markdown is totally fine – at least for me.

But – thanks for considering this as a potential feature :) It is not urgent but I feel always nicer for readers to have an open access alternative to the DOIs (of non-OA Journals).

**Comment by goerz** [comment]
I'd also be strongly inclined to add support for the [`eprint` and  `archivePrefix` fields](https://info.arxiv.org/help/hypertex/bibstyles/index.html), which are supported in RevTeX (see the section "arXiv.org support" in the [Author's Guide](https://ctan.math.illinois.edu/macros/latex/contrib/revtex/auguide/auguide4-2.pdf)). That way, you wouldn't need to worry about URLs in note fields.

**Comment by kellertuer** [comment]
That would also be great 😊

**Comment by goerz** [comment]
Implemented in #32
