### ISSUE TITLE
This package fails PkgEval

### ISSUE THREAD

**Issue by lgoettgens** [JuliaDocs/DocumenterCitations.jl#50]
See https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_date/2023-10/15/DocumenterCitations.primary.log

I think the problem is that `Pkg` is used for the documentation/doctests somewhere, but is not declared a dependency/test-dependency/docs-dependency.

**Comment by goerz** [comment]
I can reproduce it locally, but this doesn't seem actionable.

[Slack](https://julialang.slack.com/archives/C01FHUY9X96/p1697610789815359) suggested it might a bug in Nightly, but `julia --project bin/test_package.jl --name=DocumenterCitations --path=/home/goerz/Documents/Programming/DocumenterCitations.jl --julia=1.9.3` also fails.

Adding `Pkg` to both `Project.toml` and `test/Project.toml` doesn't do anything.

My suspicion is that this might be the issue described in https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/200

I don't really know what weird things `PkgEval` does internally, so this kinda seems like a problem for the JuliaHub people to solve on their end.

I'm going to tag this as invalid, but keep it open (at least for a while).

If @pfitzseb or @mortenpi tell me what I have to do to make `PkgEval` work, I'll be happy to do that ;-)

**Comment by pfitzseb** [comment]
cc @maleadt

**Comment by goerz** [comment]
It's gotta be some interaction between how Documenter evaluates `@eval` blocks and `PkgEvals` sandboxing

**Comment by goerz** [comment]
One thing I could do is to wrap that `@eval` block into a try/catch. It's not essential for testing (it just displays the version badge on the documentation).

While I was trying that, I found that the `--path` option to `bin/test_package.jl` apparently doesn't work, or at least `PkgEval` isn't picking up on my modifications to the package source. So when I said that adding `Pkg` to `Project.toml` doesn't help, that may not have been true 🤷

**Comment by maleadt** [comment]
> I don't really know what weird things `PkgEval` does internally, so this kinda seems like a problem for the JuliaHub people to solve on their end.

PkgEval is a community service, and is not related to JuliaHub. The code is public: https://github.com/JuliaCI/PkgEval.jl
You can see that it just uses `Pkg.test`, so it doesn't do anything weird internally: https://github.com/JuliaCI/PkgEval.jl/blob/2831046f1407eda2b403824b93cd1e08b25d9d70/src/evaluate.jl#L481

**Comment by goerz** [comment]
Fair enough... Indeed, just doing `Pkg.add("DocumenterCitations"); Pkg.test("DocumenterCitations")` in a temporary environment also fails with the same error. I still don't understand *why*, but at least that's something that's easier to test with.

**Comment by goerz** [comment]
I'll leave this issue open until after the next release, when I've confirmed that the `PkgEval` badge has turned green on https://juliahub.com/ui/Packages/General/DocumenterCitations

**Comment by goerz** [comment]
Thanks to the discussion at https://discourse.julialang.org/t/how-does-the-pkgeval-badge-work-on-juliahub/105662, I've added a workflow in #66 that checks the PkgEval status as part of the release process.
