### ISSUE TITLE
Support `urldate` field

### ISSUE THREAD

**Issue by goerz** [JuliaDocs/DocumenterCitations.jl#53]
@Seelengrab requested support for the `urldate` field in https://github.com/JuliaDocs/DocumenterCitations.jl/pull/52#issuecomment-1776715197.

In principle, adding "accessed on" information can already be done with the `note` field, so I'd like to clarify the motivation for supporting an additional `urldate` field and its expected behavior.

I could think of the following two motivations:

1. Citation management software like Zotero may export `urldate` automatically, and it would be convenient not to have to re-edit the information into the `note` field.
2. A "smart" `urldate` field could ensure consistent rendering of the "accessed on" date.

I'd consider especially the second point as a good reason to have a `urldate` field. That is, `urldate` should be processed in some non-trivial way. For this to work,

* The `urldate` field *must* be in the format `YYYY-MM-DD`. I checked that this is the case for `biblatex`: it will ignore anything in a different format.
* The date will be parsed and validated, and rendered as, e.g., "Accessed on `<human-readable-date>`", where `<human-readable-date>` is reformatted from the original `YYYY-MM-DD`. It seems like `biblatex` uses the American `MM/DD/YYYY` (maybe that depends on my locale settings), but since this is generally ambiguous, I'd probably opt for "Oct 24, 2023"

**Comment by Seelengrab** [comment]
I was just about to open the issue :joy: 

As far as "how should it render" goes, I'd default to whatever ISO 8601 does (probably through the Dates stdlib?) with the option of passing a `DateFormat` for output with `Dates.format`.

**Comment by goerz** [comment]
Well, [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html) strictly speaking is `YYYY-MM-DD`, or even `YYYY-MM-DD HH:MM:SS.sss`, which is great for technical purposes, but not something I'd be keen on putting in a human-readable bibliograhic reference.

But yes, we'll use `Dates.format`:

```
julia> import Dates

julia> d = Dates.Date("2015-01-01")
2015-01-01

julia> fmt = Dates.DateFormat("u d, Y", "english")
dateformat"u d, Y"

julia> Dates.format(d, fmt)
"Jan 1, 2015"
```

There'll be a setting to change the `DateFormat` in a custom style, but I'd go with the above for the default styles.
