### ISSUE TITLE
Link checking with DocumenterCitations

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaDocs/DocumenterCitations.jl#58]
Link checking errors when using citations from
https://github.com/ali-ramadhan/DocumenterCitations.jl

**Comment by mortenpi** [comment]
I took the liberty of transferring the issue, but maybe this should be closed instead.

**Comment by odow** [comment]
Yes, since there wasn't a concrete example from OP, you should close this issue (I don't have permission). But anyone reading this who encounters a similar issue should either comment below, or open a new issue.

**Comment by goerz** [comment]
I'd consider "Add a test that checks that invalid links trigger the link checker" as the actionable item for closing this.

**Comment by goerz** [comment]
Trying to add a test uncovered that, in fact, the link checker does *not* traverse into the bibliography.

That's a bug, and should be fixed.

**Comment by goerz** [comment]
This will require a fix in `Documenter`: https://github.com/JuliaDocs/Documenter.jl/issues/2329

**Comment by goerz** [comment]
As soon as https://github.com/JuliaDocs/Documenter.jl/pull/2330 is merged, I'll be able to fix this
