### ISSUE TITLE
the new default style can cause ugly results

### ISSUE THREAD

**Issue by Krastanov** [JuliaDocs/DocumenterCitations.jl#7]
@goerz asked for testers in another pull request here.

Everything seems to work fine, and I actually prefer the new style, but I need to edit my documents for the new style to look good, so maybe a different default should be considered.

## release version of DocumenterCitations with default options

![image](https://github.com/JuliaDocs/DocumenterCitations.jl/assets/705248/e7475b26-2138-4381-86c7-4a7db735f0a7)

## master branch of this repository

![image](https://github.com/JuliaDocs/DocumenterCitations.jl/assets/705248/9a93a13d-ee0b-4495-b1ee-58006e6a7f4d)

As I mentioned, I actually prefer what I can do with the new style, so I will be editing my documentation to use the new style. However, the new style does seem to break things if left on as default.

**Comment by goerz** [comment]
Yes, no question. I think we came down on making it a breaking release with the new numeric style as default. Can you check that everything is okay if you use `style=:authoryear`? In a case like yours, that would be the intended “upgrade path”, and then you’ll have to rewrite things a bit for the new numeric style. 

Personally, I don’t care very much what the default is, except that changing it to `:authoryear` would imply that the documentation has to be restructured pretty substantially, and people seem eager to get this release out the door.

**Comment by Krastanov** [comment]
Yes, that looks great! A breaking release sounds great to me!

**Comment by goerz** [comment]
For rewriting your documentation in the `:numeric` style, simply replacing some of the `@cite` commands with `@citet` or `@citet*` might already do the trick. Otherwise, I'd probably write out the lists of publications manually as described in the section on [Citations in docstrings](https://juliadocs.org/DocumenterCitations.jl/dev/syntax/#Citations-in-docstrings).

**Comment by goerz** [comment]
One thing we could consider to further mitigate the breakage: Maybe in the 1.0 release, if someone instantiates `CitationBibliography` without an explicit `style` keyword argument, we should emit a warning. This is going to be every existing user who updates the plugin but doesn't touch their `docs/make.jl`. The `@warn` message would indicate that the default style has changed in the 1.0 release and that the pre-1.0 behavior can be restored by passing `style=:authoryear`.

**Comment by goerz** [comment]
BTW, you might want to make a PR to add your project to https://github.com/JuliaDocs/DocumenterCitations.jl/blob/master/docs/src/index.md#examples (now or after the next release)
